### ISSUE TITLE
Listing unused rules and unused terminals

### ISSUE THREAD

**Issue by robstewart57** [haskell/happy#17]
I'm sure I'm missing something obvious with the invocation of happy.

```
happy -gca MyGrammar.y
unused rules: 23
unused terminals: 3
shift/reduce conflicts:  9
reduce/reduce conflicts: 37
```

Great, it identified 23 unused rules and 3 unused terminals. How do I ask happy to _list_ them?

**Comment by mrexodia** [comment]
`--info` does not list anything for me
