### ISSUE TITLE
Move to Haskell github organziation

### ISSUE THREAD

**Issue by Ericson2314** [haskell/happy#177]
@bgamari was thinking we move Happy and Alex to the Haskell organization, now that they are maintained by multiple people / becoming increasingly community endeavors. That sounds good to me. What do the rest of you all think?

**Comment by int-index** [comment]
How does one become a member of that organization?

**Comment by Ericson2314** [comment]
@int-index I don't know, but it need not completely matter, because we can keep our per repo permissions. I think the point is basically to make things more discoverable, and make it easier to pick new maintainers if we all disappear at once.

**Comment by Ericson2314** [comment]
I should also say the Haskell gitlab could be another possible destination, but one that makes dealing with the issues slightly harder. I leave it @bgamari and others to way the merits of that vs github haskell org.

**Comment by andreasabel** [comment]
@Ericson2314 @int-index @simonmar 
I infer from this issues that maintainership for `happy` is changing or has changed or is at least expanding.
Could you please update the `README` to clarify who are the maintainers?
I think it is good if that information is public and easily available.

**Comment by Ericson2314** [comment]
Sure.

**Comment by Ericson2314** [comment]
OK added a section to Alex and Happy alike. I wasn't quite sure how to do word it, but my understanding is  @int-index and I are meant to be the more active maintainers, while @simonmar is the maintainer of last resort with the most authority. I just put in bullets for now.

**Comment by Ericson2314** [comment]
Thinking about it more, I think we should start with github.com/haskell/. Since the move to their doesn't break the proprietary metadata I see no "remorse" in doing that but later moving to https://gitlab.haskell.org, but I do see the remorse in moving from https://gitlab.haskell.org and then back to github. That sways me, for now.

**Comment by bgamari** [comment]
This sounds fine to me. @simonmar, could you effect this change?

**Comment by Ericson2314** [comment]
This has been done!
