### ISSUE TITLE
Website (haskell.org/happy) is out of date

### ISSUE THREAD

**Issue by Martinsos** [haskell/happy#195]
Upon typing `haskell happy` into search engine, first hit for me is haskell.org/happy, however the page doesn't seem to have been updated since 2010. This gives an impression that project stopped in 2010, which doesn't seem to be the case as I see here on github repo that there are new releases, latest one from 2020. Also, there is no link on the webpage that points to the github repo.

While I understand that updating all information on the webpage might be a big task, would it be possible to at least update the "News" section with new releases, fix couple of broken links, and mention somewhere at the top that source is currently available on the github? If nothing else, at least we could put a note mentioning that the webpage is out of date and link to github repo.

I could make a PR, however I haven't seen code of the webpage being present in this repo. What is the method that could be used to propose a patch for the webpage? Thanks!

**Comment by andreasabel** [comment]
See also #122 and #44.

**Comment by askeblad** [comment]
At least 1 Linux distro (default full install) includes `docbook`, but would require `Sphinx` and its 10 dependencies if converted.

**Comment by ulysses4ever** [comment]
I don't see why the number of additional dependencies in an unsaid Linux distribution should be an argument I'm this discussion. By extension, let's all switch from Haskell to C, because some Linux distribution has a C compiler by default, but no GHC. 

The friction introduced by an ancient XML-based format like docbook is unthinkable by today's standards. Please, convert to something human-readable and editable, also having a modern UI, like readthedocs.

**Comment by andreasabel** [comment]
I tried conversion with `pandoc` and hit:
- https://github.com/jgm/pandoc/issues/7938
  ```
  $ pandoc -f docbook -t rst -s happy.xml 
  Invalid XML:
  UnresolvedEntityException (fromList ["dollar","ldquo","mdash","percnt","rdquo"])
  ```

**Comment by Martinsos** [comment]
Thanks for taking this on @andreasabel ! Let me know if I can help in any way.

**Comment by askeblad** [comment]
@andreasabel 

happy.xml

dollar `&#x24;`, ldquo `&#x201C;`, mdash `&#x2014;`, percnt `&#x25;`, rdquo `&#x201D;`

alex.xml

```
$ ./pandoc -f docbook -t rst -s alex.xml
Invalid XML:
UnresolvedEntityException (fromList ["lsquo","nbsp","rsquo"])
$ 
```

lsquo `&#x2018;`, nbsp `&#xA0;`, rsquo `&#x2019;`

**Comment by askeblad** [comment]
> number of additional dependencies

packages periodically obliging version updates, or for a system install use of a virtual environment

```
$ python3 -m venv ghc_env
$ ghc_env/bin/python3 -m pip install --upgrade pip --quiet
$ ghc_env/bin/python3 -m pip install Sphinx --quiet
$ su
Password: 
# chown -R root:root ghc_env
# source ghc_env/bin/activate
(ghc_env) # 
```

**Comment by andreasabel** [comment]
https://www.haskell.org/happy/  now redirects to  https://haskell-happy.readthedocs.io/en/latest/
