### ISSUE TITLE
Happy refactoring (happy-1.21): either move forward or take it back

### ISSUE THREAD

**Issue by andreasabel** [haskell/happy#255]
ATTN: @Ericson2314 @int-index 

`happy-1.21` included large refactorings, was released in October 2021 but then unreleased shortly after.  It is soon that this is two years ago.

Unfortunately, in the current state, with refactorings applied but a boot-strapping problem persisting, `master` is not releasable.  This also means that fixing issues is stalled, as the fate of those fixes would be unknown.

I only see two options now:
1. Either finish to work done in 2021 to bring it to a releasable state.
2. Or take this work back and bring `master` back into a releasable state based on the `happy-1.20` code.

Since I am mostly interested in the stability of `happy`, I don't care much which path is taken.  However, I think that something has to happen soon.

**Comment by int-index** [comment]
I've lost all context by now. What would it take to make `happy` releasable without reverting the refactorings?

**Comment by andreasabel** [comment]
I think the context can be recovered by starting here:
- #211

**Comment by int-index** [comment]
OK. This really is an issue with Cabal, but we can work around it. We need a custom script to generate release tarballs with `Bootstrapped.hs` pre-generated from `Bootstrapped.ly`. I'll try to do it and see how well it works.

**Comment by andreasabel** [comment]
Note that currently (1.20) one has to `make sdist` to make a custom tarball as well.  (Plain `cabal sdist` does not generate a boot-strappable tarball.)  Maybe something similiar can be put in place for 1.21.

**Comment by Ericson2314** [comment]
Yeah you are right @andreasabel, this has dragged on long enough.

**Comment by int-index** [comment]
See https://github.com/haskell/happy/issues/238#issuecomment-1925340557
