### ISSUE TITLE
Can't figure out how to run tests in parallel

### ISSUE THREAD

**Issue by sgraf812** [haskell/happy#264]
The test.hs script calls make with `-j` set to the number of capabilities of the script process. I can't seem to figure out how to increase that number; at the least it does not pick up the number of cpu cores on my machine automatically.
It's a bit annoying, but not too bad: I can just change the script to use `-j7` (I have 6 cores). Nevertheless, the script seems a bit misleading.

**Comment by andreasabel** [comment]
https://github.com/haskell/happy/blob/abcd8c02204bb7d1865128a6f0debcd5ab880d79/test.hs#L6-L9

**Comment by sgraf812** [comment]
I have tried, but it is unclear to me where I should pass it. Is it `cabal test +RTS -N7`? No (I tried). More likely I'll have to do `cabal test --test-options="+RTS -N7 -RTS"` but that errors out with ... aha, a useful message:

```
tests: the flag -N7 requires the program to be built with -threaded
```

Fix incoming.
