### ISSUE TITLE
Bold change: Continue supporting LR's `--array --ghc --coerce` mode, abandon the rest

### ISSUE THREAD

**Issue by sgraf812** [haskell/happy#268]
The happy LR backend has  24 different modes, making it quite insane to maintain and extend. These 24 modes depend on

   * whether you want to provide your own lexer or simply have a `[Token]` available
   * whether you want to have a monadic parser
   * whether you want to generate a table-based parser (`--array`) or a recursive ascent parser with explicit stack (i.e., generate Haskell code, the default). `--array` based parsers tend to be introspectable (this is huge) and smaller but a bit slower. (The latter seldomly matters for an LR parser, because the language it parses will need name resolution and type checking as well.) 
   * whether you want to target GHC (`--ghc`) for using unboxed integers and bytestrings (in `--array` mode)
       * and if so, whether you want to use `unsafeCoerce` for another performance boost (`--coerce`)
         
Realistic applications only ever tend to use `--array --ghc --coerce`. I suggest we abandon the non-array, non-ghc modes to get down to a more manageable 4 modes, not least because it also means we can get rid of the mandatory `{-# LANGUAGE CPP #-}` that is currently emitted: https://github.com/haskell/happy/issues/263 Ironically, that means that even the code generated *without* passing `--ghc` is GHC dependent. Plus, I don't have any plans to make error resumption work in recursive ascent mode, because the stack unwinding necessary would need a lot of work that is entirely orthogonal to the table-based mechanism.

**Comment by sgraf812** [comment]
For context, I proposed bringing #272 (which introduces other breaking changes around `%errorhandler explist`) into a mergeable state and applying the result to GHC as a [GSoC proposal](https://github.com/haskell-org/summer-of-haskell/blob/1eb940520859f17d73103cbc162d2dcfeb73f6a1/content/ideas/parse-error-recovery.md).

It would probably be good to fix this issue as the first action before we rebase #272 on top of it and would likely lead to simplifications of #272 in turn. For example, we could finally give accurate type signatures in the template file rather than generating them from `happy` only if we need them for disambiguation purposes (because it is so painful to do so).

Either way, this work would probably be bound for `happy-3.0`, as I think we should not hold back a 2.0 release featuring just the split packages. One breaking change after another...

**Comment by sgraf812** [comment]
What do the other maintainers think? @int-index @Ericson2314 any strong opinions? I think it would make the template files *much* simpler if we could just assume that it's OK to unbox integers, user coercions, etc.

It would also make the life of @Kariiem much simpler, who is the GSoC student working on `happy` this summer.

**Comment by int-index** [comment]
> any strong opinions?

I feel rather strongly that we should retain the option of generating safe code without `unsafeCoerce`. The remaining configuration space can be reduced.

**Comment by sgraf812** [comment]
The main payload of this proposal has been implemented in #276 and #278.

One remaining question is whether we should somehow notify people of the change when they pass `-g` or `-a`. On the other hand, people who *do not* pass `-g` or `-a` potentially are affected much more.

**Comment by sgraf812** [comment]
I want to ask for feedback regarding @andreasabel excellent suggestion

>  I'd still keep the command line options [for -ag] but emit a warning that these are obsolete now.

This sounds like a good idea in principle, but shouldn't we rather (or also) warn when the flags are *omitted* rather than when they are *present*? That is, we could warn

1. when the flags are present, because they are slated for removal in a future release
2. when the flags are omitted, because we now generate different code that might no longer compile on non-GHC configurations.

I think (1) is what Andreas suggested, which makes sense. (2) on the other hand depends on whether we regard the payload here as a breaking change. I think we do, do we?

Then perhaps `happy` should *always* warn, for both (1) and (2)? Should we provide a temporary flag to *suppress* these warnings?

**Comment by phadej** [comment]
> Well, if the final target is to remove these options,

Please don't, if it's not a must. It will make e.g. `Cabal`'s life harder (AFAIK currently iit doesn't care much about `happy` version).

**Comment by andreasabel** [comment]
Cabal always passes `-g`, so yes, removal would cause extra work there (and probably in tons of other user code), so keeping these options in as _always on_ is the most backward compatible way.

For stable tools like `happy` one has to resist any cleanup urges.

**Comment by sgraf812** [comment]
I was toying with adding a flag `--api-level=2` to silence the warning (2). But ultimately that is just like passing `-ag` in the first place if we never remove `-ag` (which I second).

So we should emit a warning if `-g` is not present, indicating that breaking changes are to be expected since happy >= 2.0 assumes `-g` (and `-a`, but that is rather an internal change).

**Comment by sgraf812** [comment]
#290 provides the fix. Example warning:

```
Warning: With happy 2.0, the --ghc flag has become non-optional. To suppress this warning, pass the --ghc flag.
```
