### ISSUE TITLE
Question: monadic actions and attributes?

### ISSUE THREAD

**Issue by snizzo** [haskell/happy#282]
Hi!

Is it possible to use a monadic action and specify an attribute in a grammar rule?

Example:
`MyRule { %myMonadicAction }`

I'd like to do something like this:
```
MyRule { %myMonadicAction
                ; $$.myattr = 1 }
```

Is this possible? I didn't find anything useful explaining this. I've seen in the source there are 2 different parsers for attributed and non attributed grammar but couldn't find an answer. Thank you very much!

**Comment by snizzo** [comment]
I tried with your instruction and:
`MyRule : {% myMonadicAction; $$.myattr = 0 }`

doesn't work. Terminal says:
`MyParser.y: 134: error in attribute grammar rules: Parse error`. I guess happy isn't able to parse that.

**Comment by sgraf812** [comment]
> I tried with your instruction and:
> `MyRule : {% myMonadicAction; $$.myattr = 0 }`

But that is not what I wrote. I wrote

> In your case, `MyRule {% do myMonadicAction; $$.myattr = 1 }` should work

Note the use of `do` that your snippet is missing.

**Comment by snizzo** [comment]
Yes, I tried a lot of combinations but couldn't get past an happy parse error.

```haskell
%attributetype { MyAttributes a }
%attribute value { a }
%attribute num   { Int }

%%


Integer  : L_integ  { $$ =  (read $1) :: Integer; $$.num = 0 }

Program : BEGINMARKER Integer ENDMARKER { $$ = Prog $2; $$.num = 0 }

BEGINMARKER : {-empty-} {% do beginBlock; $$.num = 0}
ENDMARKER : {-empty-} {% do endBlock; $$.num = 0}
```
The code above doesn't work and result in this output from happy:
```bash
happy -gcai ParLang.y
ParLang.y: 101: error in attribute grammar rules: Parse error

ParLang.y: 165: error in attribute grammar rules: Parse error


make: *** [Makefile:26: ParLang.hs] Error 1
```
Line 101 and 165 refers to the subsequent line to BEGINMARKER and ENDMARKER rules.

-----
Instead, the not attributed grammar works perfectly with monadic actions, and the attributed one works perfectly without the monadic actions. It's the mix that doens't get through and I can't get where I'm failing.

**Comment by sgraf812** [comment]
Apologies, I was somehow repeatedly missing that you were talking about the parser for *attribute grammars*.

Looking at the grammar file for the attribute grammar parser it appears there is no case for "just code":
https://github.com/haskell/happy/blob/f5a5fb1ce9e9ad7e6411eeb05cffd368d7ff5ef5/packages/frontend/boot-src/AttrGrammarParser.ly#L41-L45

But I think you are supposed to use `where` in that case, which embeds a monadic action of type `m ()`. If you just want a side-effect, simply do not fail. In your example, some variation of the following should work:

```
%attributetype { MyAttributes a }
%attribute value { a }
%attribute num   { Int }

%%


Integer  : L_integ  { $$ =  (read $1) :: Integer; $$.num = 0 }

Program : BEGINMARKER Integer ENDMARKER { $$ = Prog $2; $$.num = 0 }

BEGINMARKER : {-empty-} { where beginBlock; $$.num = 0 }
ENDMARKER : {-empty-} { where endBlock; $$.num = 0 }
```

Sadly, the [only](https://github.com/haskell/happy/blob/master/tests/AttrGrammar001.y) [two](https://github.com/haskell/happy/blob/master/tests/AttrGrammar001.y) test cases are non-monadic and hence do not really have side-effects, but they *do* use `where` rules.

**Comment by sgraf812** [comment]
@snizzo did my previous comment resolve your issues? Would you be so kind to submit a test case enshrining your solution?
