### ISSUE TITLE
Error Building Happy: The program 'happy' is required but it could not be found

### ISSUE THREAD

**Issue by Boring545** [haskell/happy#285]
Here's the process I followed to build happy, ending with the reported error:

```
wget https://hackage.haskell.org/package/happy-1.20.1/happy-1.20.1.tar.gz
tar -xf happy-1.20.1.tar.gz
cd happy-1.20.1

ghc --make Setup.hs
./Setup configure --user --enable-library-profiling
```

Attempt to build happy, resulting in the following error:

```
./Setup build
Preprocessing executable 'happy' for happy-1.20.1..
Error: Setup: The program 'happy' is required but it could not be found
```

Additionally, I successfully built Alex using a nearly identical approach.Is there an issue with my build method?

**Comment by Boring545** [comment]
I tried all versions starting with 1.2, and they all failed during the process. Finally, I tried https://hackage.haskell.org/package/happy-1.19.12/candidate/happy-1.19.12.tar.gz, and the build was successful.

**Comment by sgraf812** [comment]
Indeed, 1.20.1.1 should work. 1.21.0 and 1.20.1 were deprecated for the very reason that they can't be built.

**Comment by sgraf812** [comment]
@Boring545 is there anything left to do here? Perhaps adding documentation somewhere? Where?

I see that you were using `wget` to download the tarball. Why not `cabal get happy`? That would have automatically downloaded the correct version.
