### ISSUE TITLE
tag: v2.0, tag: delete

### ISSUE THREAD

**Issue by andreasabel** [haskell/happy#308]
@sgraf812 : Did you intend to delete tag `v2.0`?  Because there is a tag called `delete`, so maybe the `git tag` invocation went wrong.

> commit ddfb7bb933a0c2d61333fe5851e7dbf8136f0818 (tag: v2.0, tag: delete)
> Author: Sebastian Graf 
> Date:   Tue Sep 17 12:10:04 2024 +0200
>
>    Extract common stanza in happy-lib, fix deprecation warning

**Comment by sgraf812** [comment]
Indeed; I had typed `git tag delete v2.0` at one point and thought I had fixed it already, but apparantly forgot to delete them in my local checkout as well. I deleted the tags again. Thanks for double-checking.

**Comment by andreasabel** [comment]
Thanks!
