### ISSUE TITLE
Yesod stack build error due to Happy on Windows

### ISSUE THREAD

**Issue by GiregL** [haskell/happy#323]
Hi

I am trying to start a Yesod project on Windows (11).
I created the project with the `stack new my-project yesodweb/sqlite` command line.
Then, I wanted to build it with `stack build` and I got this message while compiling:

```
happy > C:\Users\...\AppData\Local\Programs\stack\x86_64-windows\ghc-9.2.8\mingw\bin\strip.exe: unable to rename 'C:\Users\...\AppData\Roaming\stack\snapshots\2781983c\bin\happy.exe'; reason: Invalid argument
```

I didn't change the project configuration other than uncomment `system-ghc: true` in the stack.yaml file.

And here is my environment setup:
- GHCup 0.1.22.0
- Stack 2.15.5
- HLS   2.9.0.1
- cabal 3.10.3.0
- GHC   9.4.8      recommended,base-4.17.2.1

How can this be fixed ?

**Comment by sgraf812** [comment]
I actually have no idea what is going on. Are you sure this the fault of Happy rather than some quirky interaction between `stack` and Windows? What version of Happy are you using?
